name: MTTTEnv
channels:
  - anaconda
dependencies:
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - python=3.6
  - numpy=1.16.3
  - tensorflow-gpu=1.13.1
  - tensorflow=1.13.1
  - tensorboard=1.13.1
  - matplotlib=3.0.3
  - sphinx=2.0.1
  - scikit-image=0.15.0
  - pympler=0.7
  - humanize=0.5.1
  - scikit-learn=0.20.3
  - keras=2.2.4
  - pip=19.1.1
  - pip:
      - gin-config == 0.1.4
  